apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  labels:
    app: azdevops-agent
spec:
  replicas: 2
  selector:
    matchLabels:
      app: azdevops-agent
  template:
    metadata:
      labels:
        app: azdevops-agent
    spec:
      imagePullSecrets:
      - name: acr-secret  
      containers:
      - name: azdevops-agent
        #nome do seu ACR que foi criado
        image: acragentspool.azurecr.io/azure-devops-agent:latest
        resources:
          requests:
            cpu: "1"
            memory: 1024Mi
          limits:
            # cpu:  no CPU limit!
            # memory: 8192Mi
            memory: 4096Mi
        env:
          - name: AZP_URL
            value: "https://dev.azure.com/rafaelribeiroAG"
          - name: AZP_POOL
            value: "k8sAgentsPool"
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: pipeline-auth
                key: personalAccessToken