apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JhZ2VudHNwb29sLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3JhZ2VudHNwb29sIiwicGFzc3dvcmQiOiJCMHRWUVhzRWw1TFBTVlNLdC9jMHJsS1crU243RHZPOWpXazc1SlRIL0YrQUNSQTNtakhkIiwiYXV0aCI6IllXTnlZV2RsYm5SemNHOXZiRHBDTUhSV1VWaHpSV3cxVEZCVFZsTkxkQzlqTUhKc1MxY3JVMjQzUkhaUE9XcFhhemMxU2xSSUwwWXJRVU5TUVROdGFraGsifX19

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pipeline-auth
data:
  personalAccessToken: cTJrbjRmZ29ldWtmb25jaGh0eGhxZGljZDJwNHNwdm1kZ3pxM2ZhenZ6b2V5bGNuNXBzYQo=