apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJhY3JhZ2VudHNwb29sLmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJhY3JhZ2VudHNwb29sIiwicGFzc3dvcmQiOiJOZ3c4YXdweDlKa2RCL3hjVkdTNFNLY2FvODQxSVNIRFlYSVVaUGhiT3ArQUNSRG44QW8wIiwiYXV0aCI6IllXTnlZV2RsYm5SemNHOXZiRHBPWjNjNFlYZHdlRGxLYTJSQ0wzaGpWa2RUTkZOTFkyRnZPRFF4U1ZOSVJGbFlTVlZhVUdoaVQzQXJRVU5TUkc0NFFXOHcifX19
# the above secretwas obtained by doing:
# kubectl create secret docker-registry <SECRET_NAME> --docker-server=<REGISTRY_NAME>.azurecr.io --docker-username=<USERNAME> --docker-password=<PASSWORD> --dry-run=client -o yaml
